config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  # get "tasks/new", to: "tasks#new", as: "new_task"
  # post "tasks", to: 'tasks#create'

  # delete "tasks/:id", to: "tasks#destroy"

  # get "tasks/:id", to: "tasks#show", as: 'task'

  # get    "tasks/:id/edit", to: "tasks#edit", as: 'edit_task'
  # patch  "tasks/:id",      to: "tasks#update"

  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end


  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    @task.save!
    redirect_to root_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to root_path
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |task| %>
<div class="form-group">
  <%= task.label :title %>
  <%= task.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= task.label :details %>
  <%= task.text_field :details %>
</div>
<div class="form-group">
  <%= task.label "Completed" %>
  <%= task.check_box :completed, class: 'form-control' %>
</div>

  <%= task.submit class: 'btn btn-primary'%>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <% checked = task.completed ? 'checked' : '' %>
    <li><input type='checkbox' <%= checked %> /> <%= link_to task.title, task_path(task.id) %>
      <button type="button"><%= link_to "delete", task_path(task.id), method: :delete, data: { confirm: "Are you sure?" } %></button>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a task', new_task_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<% if @task.completed %>
  <p><%= 'Done' %></p>
  <% else %>
  <p><%= 'Not Done' %></p>
  <% end %>


<h2><%= @task.details %></h2>
<br>
<%= link_to raw('<button class="button-edit" type="button">Edit Task</button>'
), edit_task_path %>
<br>
<br>
<br>
<%= link_to 'back to home', root_path %>